### ISSUE TITLE
B2B blackouts

### ISSUE THREAD

**Issue by magalhaesjr** [magalhaesjr/NVC-Scheduler#17]
# Summary
Selecting back-to-back blackout dates in reverse order causes a crash

## To reproduce
- Select furthest date first
- Then select the week before as a blackout

## Details
Message produced: 
```shell
template.js:369 Uncaught TypeError: Cannot read properties of undefined (reading 'date')
    at Template.<anonymous> (template.js:369:77)
    at Array.forEach (<anonymous>)
    at Template.updateTeamPreview (template.js:366:41)
    at Template.updateSchedule (template.js:520:10)
    at Template.addBlackout (template.js:456:10)
    at toggleBlackout (scheduler.js:923:20)
    at HTMLInputElement.<anonymous> (scheduler.js:383:53)
```

**Comment by magalhaesjr** [comment]
Resolved in `v2.0.0`
